### ISSUE TITLE
HA 2023.7 breaking changes?

### ISSUE THREAD

**Issue by Steaders1965** [jacekk015/zha_quirks#14]
Since updating to 2023.7 I've been getting this error:

Logger: zhaquirks
Source: custom_zha_quirks/ts0601_trv_beca.py:69
First occurred: 22:39:21 (1 occurrences)
Last logged: 22:39:21

Unexpected exception importing custom quirk 'ts0601_trv_beca'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py", line 454, in setup
    importer.find_module(modname).load_module(modname)
  File "< frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "< frozen importlib._bootstrap_external>", line 1120, in load_module
  File "< frozen importlib._bootstrap_external>", line 945, in load_module
  File "< frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "< frozen importlib._bootstrap>", line 721, in _load
  File "< frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "< frozen importlib._bootstrap_external>", line 940, in exec_module
  File "< frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_zha_quirks/ts0601_trv_beca.py", line 69, in <module>
    class BecaManufCluster(TuyaManufClusterAttributes):
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 165, in __init_subclass__
    raise TypeError(f"Duplicate definitions exist for {duplicates}")
TypeError: Duplicate definitions exist for ['boost_duration_seconds']

Looks similar to #12

**Comment by jacekk015** [comment]
That was a typo... newest HA checks for duplicates... and sometimes finds them.
Corrected in latest version.
