### ISSUE TITLE
ts0601_trv_maxsmart  ZHA  can't load zhaquirks

### ISSUE THREAD

**Issue by maksimvelbaum** [jacekk015/zha_quirks#16]
Hi , 

Any chances to solve this problem ? 

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3

Logger: zhaquirks
Source: /usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py:456
First occurred: 16:31:25 (1 occurrences)
Last logged: 16:31:25

Unexpected exception importing custom quirk 'ts0601_trv_maxsmart'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py", line 454, in setup
    importer.find_module(modname).load_module(modname)
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_zha_quirks/ts0601_trv_maxsmart.py", line 91
    <title>zha_quirks/ts0601_trv_maxsmart.py at main · jacekk015/zha_quirks · GitHub</title>
                                                     ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by jacekk015** [comment]
Better download that file again.
There's no line:
`<title>zha_quirks/ts0601_trv_maxsmart.py at main · jacekk015/zha_quirks · GitHub</title>`
in the code.

You can see it yourself:
https://github.com/jacekk015/zha_quirks/blob/17033c8de6ef036af6f5b148b046e3f8e4076548/ts0601_trv_maxsmart.py#L91

**Comment by maksimvelbaum** [comment]
Hi , 
Thanks , it worked , looks like linux did something when I  downloaded file or uploaded to HA,  did same operation on Windows and all working.

**Comment by jacekk015** [comment]
Glad it worked.
