### ISSUE TITLE
Import error for ts0601_trv_maxsmart.py

### ISSUE THREAD

**Issue by Ja-Ju** [jacekk015/zha_quirks#31]
Hello jacekk015,
I am using your custom quirk to integrate thermostats from lidl.
After one of them worked reliable, I wanted to update to the new version of the quirk.
Unfortunately the import fails with the followig error:

Logger: zhaquirks
Source: custom_quirks/ts0601_trv_maxsmart.py:1
First occurred: 09:39:55 (1 occurrences)
Last logged: 09:39:55

Unexpected exception importing custom quirk 'ts0601_trv_maxsmart'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py", line 454, in setup
    importer.find_module(modname).load_module(modname)
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_quirks/ts0601_trv_maxsmart.py", line 1, in <module>
    {"payload":{"allShortcutsEnabled":false,"fileTree":{"":{"items":[{"name":"LICENSE","path":"LICENSE","contentType":"file"},{"name":"README.md","path":"README.md","contentType":"file"},{"name":"trv_saswell.py","path":"trv_sasw

...

},"title":"zha_quirks/ts0601_trv_maxsmart.py at 30228a0a130ca84b209c5b45d885dd135de4177e · jacekk015/zha_quirks"}
                                      ^^^^^
NameError: name 'false' is not defined

![image](https://github.com/jacekk015/zha_quirks/assets/58516039/6fdf0418-ad42-45ec-bb34-719dfb7ebbcb)

**Comment by jacekk015** [comment]
Not possible, because I use it myself for my TRV's.
Be sure you're downloading RAW file and not a html version
https://github.com/jacekk015/zha_quirks/raw/main/ts0601_trv_maxsmart.py

**Comment by Ja-Ju** [comment]
Interesting.. I tried it just with "wget https://github.com/jacekk015/zha_quirks/blob/a5489f5418befbbb0c74a084d02feedafdf18003/ts0601_trv_maxsmart.py"
This didn't work. Now I copied the content in nano and saved it locally - afterwards the import worked. Thanks for the quick answer!
