### ISSUE TITLE
TS0601 from _TZE204_aoclfnxz difference from current temp to temp setpoint to start heating

### ISSUE THREAD

**Issue by Dagolag** [jacekk015/zha_quirks#64]
Hello
I have the TS0601 from _TZE204_aoclfnxz. In the beginning of my smart home, I had openhab with z2m installed. The thermostat was identified by z2m and I had many settings, that were possible. 
Then I switched to HA and zha as my zigbee controller. I got the thermostat running with your custom quirk, thanks for that.
But now I have a problem, when the thermostat was running trought z2m, I configured a temperatur difference between the heating setpoint and the current temparatur. So, the thermostat now only activates the heating mode, when the current temparatur is lower than 2 degree as the setpoint is set to. When I set the heating setpoint to 21 degree, the thermostat only starts heating when the current temperatur hits 19 degree.
With the custom quirk I can't change this setting and maybe you are able to include this configuration to the quirk!?
Otherwise I have to configure a temporary z2m and try to change the setting there, but I would like not to have to do that -.-

**Comment by jacekk015** [comment]
Try updated quirk. I coded it without any of your logs, so it's possible that it will not work at first time.
HA restart is needed after file update.

**Comment by Dagolag** [comment]
Thanks for the quick response and the change.
I "installed" the new quirk but there were no changes on the three thermostat devices in my ha after restart.
I aktivated the logging from ZHA and found the following entries for my three thermostats:
`2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0000] Attribute id: 4 value: _TZE204_aoclfnxz
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0000] Attribute id: 5 value: TS0601
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 27 value: 2
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 536 value: 205
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 0 value: 2050
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 528 value: 20
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 18 value: 2000
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 1026 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 37 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 1060 value: 1
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 30 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 41 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 296 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0204] Attribute id: 1 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0000] Attribute id: 1 value: 74
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0000] Attribute id: 65506 value: 56
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0000] Attribute id: 65508 value: 0
2024-11-20 06:59:44.429 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0000] Attribute id: 65503 value: �D�.i�D�.i�D�.i�D�.i�D�.i�D�.i�D�.i�D�.i
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 257 value: 1
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0201] Attribute id: 28 value: 4
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:2:0x0006] Attribute id: 0 value: 0
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:3:0x000d] Attribute id: 85 value: -3.0
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0xef00] Attribute id: 539 value: -3
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:3:0x000d] Attribute id: 106 value: 0.1
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x3f6b:1:0x0019] Attribute id: 2 value: 74


2024-11-20 06:59:44.426 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 4 value: _TZE204_aoclfnxz
2024-11-20 06:59:44.426 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 5 value: TS0601
2024-11-20 06:59:44.426 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 27 value: 2
2024-11-20 06:59:44.426 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0xef00] Attribute id: 528 value: 21
2024-11-20 06:59:44.426 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 18 value: 2100
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0xef00] Attribute id: 1060 value: 1
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 30 value: 0
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 41 value: 0
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0xef00] Attribute id: 536 value: 200
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 0 value: 2000
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 1 value: 74
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 65506 value: 56
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 65508 value: 0
2024-11-20 06:59:44.427 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 65503 value: lD�.ilD�.ilD�.ilD�.ilD�.ilD�.ilD�.ilD�.i
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0xef00] Attribute id: 257 value: 1
2024-11-20 06:59:44.428 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 28 value: 4
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0xef00] Attribute id: 1026 value: 0
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0201] Attribute id: 37 value: 0
2024-11-20 06:59:44.433 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0005] Attribute id: 0 value: 0
2024-11-20 06:59:44.433 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0005] Attribute id: 2 value: 0
2024-11-20 06:59:44.433 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0005] Attribute id: 1 value: 0
2024-11-20 06:59:44.433 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0005] Attribute id: 4 value: 0
2024-11-20 06:59:44.467 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0005] Attribute id: 3 value: 0
2024-11-20 06:59:44.467 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 2 value: 0
2024-11-20 06:59:44.467 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 0 value: 3
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 7 value: 1
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0000] Attribute id: 6 value: 
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:2:0x0006] Attribute id: 0 value: 0
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0xef00] Attribute id: 296 value: 0
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0204] Attribute id: 1 value: 0
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x5a6b:1:0x0019] Attribute id: 2 value: 74




2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0000] Attribute id: 4 value: _TZE204_aoclfnxz
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0000] Attribute id: 5 value: TS0601
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 27 value: 2
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0xef00] Attribute id: 536 value: 195
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 0 value: 1950
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0xef00] Attribute id: 528 value: 21
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 18 value: 2100
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0xef00] Attribute id: 1026 value: 0
2024-11-20 06:59:44.430 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 37 value: 0
2024-11-20 06:59:44.431 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0000] Attribute id: 1 value: 74
2024-11-20 06:59:44.431 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0000] Attribute id: 65506 value: 56
2024-11-20 06:59:44.431 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0000] Attribute id: 65508 value: 0
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0000] Attribute id: 65503 value: �D�.i�D�.i�D�.i�D�.i�D�.i�D�.i�D�.i�D�.i
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0xef00] Attribute id: 1060 value: 1
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 30 value: 0
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 41 value: 0
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0xef00] Attribute id: 296 value: 0
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0204] Attribute id: 1 value: 0
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0xef00] Attribute id: 257 value: 1
2024-11-20 06:59:44.432 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0201] Attribute id: 28 value: 4
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x1edb:3:0x000d] Attribute id: 69 value: -10.0
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x1edb:3:0x000d] Attribute id: 65 value: 10.0
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x1edb:3:0x000d] Attribute id: 106 value: 0.1
2024-11-20 06:59:44.468 DEBUG (MainThread) [zigpy.appdb] [0x1edb:3:0x000d] Attribute id: 256 value: 851968
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x1edb:2:0x0006] Attribute id: 0 value: 0
2024-11-20 06:59:44.469 DEBUG (MainThread) [zigpy.appdb] [0x1edb:1:0x0019] Attribute id: 2 value: 74`

I'm a little bit confused that there are different attributes for each thermostat, because all of them are the same.
It seems, that the attribute id isn't 532 (first device in log has a attribute with id 539 and a value of -3, which is the value I set as Deadzone for this device trought z2m) but it could be 539 or 85.

Is there something else I could log and help you to identify the right attribute?
Is it normal that the new added deadzone isn't listed as entity after restart? Do I have to reconnect (delete and add again) the thermostat?

Thnaks :)

**Comment by Dagolag** [comment]
I have checked again, the 539/85 is the temp_calibration attribute :(

**Comment by Dagolag** [comment]
I have seen that you only have add the deadzone to the first class Avatto but my thermostats are in the second one thats named Beok.

**Comment by jacekk015** [comment]
You have the device. Set it to known value and post whole log file as attachment drag&drop.
I can't be negative value.

Best is to remove device from HA and pair like a brand new. Then the device presents all data. But you need to wait 10 minutes minimum.
Quirk file was modified.

**Comment by Dagolag** [comment]
Hey, thanks for the help.
I updated the quirk and i think you forgot to initialize the deadzone for the boek class.
Thats the log:
2024-11-20 09:23:41.216 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry /dev/ttyAMA0 for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 132, in async_setup_entry
    async with radio_mgr.connect_zigpy_app() as app:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/radio_manager.py", line 182, in connect_zigpy_app
    app = await self.radio_type.controller.new(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 238, in new
    await app._load_db()
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 110, in _load_db
    await self._dblistener.load()
  File "/usr/local/lib/python3.12/site-packages/zigpy/appdb.py", line 684, in load
    device = zigpy.quirks.get_device(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py", line 43, in get_device
    return _DEVICE_REGISTRY.get_device(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/registry.py", line 153, in get_device
    device = candidate(device._application, device.ieee, device.nwk, device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_zha_quirks/ts0601_thermostat_avatto.py", line 630, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/zhaquirks/tuya/__init__.py", line 950, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py", line 98, in __init__
    self.add_endpoint(endpoint_id, replace_device=replaces)
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py", line 115, in add_endpoint
    ep = custom_ep_type(self, endpoint_id, replacement_data, replace_device)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py", line 177, in __init__
    cluster = c(self, is_server=True)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_zha_quirks/ts0601_thermostat_avatto.py", line 518, in __init__
    self.endpoint.device.AvattoDeadzoneTemp_bus.add_listener(self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Beok' object has no attribute 'AvattoDeadzoneTemp_bus'

**Comment by Dagolag** [comment]
I added the line "self.AvattoDeadzoneTemp_bus = Bus()" to the boek class and now i have the entity! 
Thank you very much.
I will try if it is functional and came back with the feedback

**Comment by Dagolag** [comment]
Thank you very much, it's working great.
You only have to add in line 629 the initation of the deadzone class "self.AvattoDeadzoneTemp_bus = Bus()" then it's running.
And to make the new custom quirk complete, there should also be a new deadzone cluster declaration in the Avatto class to.
Thank you very much again, great work!

**Comment by jacekk015** [comment]
Quirk updated.
